- name: example role by FQCN
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: 'vcenter.lab.local'
    vcenter_username: 'Administrator@vsphere.local'
    vcenter_password: 'C0mpl3x!'
    cluster_name: 'lab'

    esxi_scg_ntp: true
    ntp1: 'de.pool.ntp.org'
    ntp2: 'us.pool.ntp.org'
  collections:
    - daftpyposh.vspherescg
  tasks:
    - name: import ESXi role from a collection
      import_role:
        name: daftpyposh.vspherescg.esxi_scg
