- name: example role by FQCN
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: 'vcenter.lab.local'
    vcenter_username: 'Administrator@vsphere.local'
    vcenter_password: 'C0mpl3x!'
    cluster_name: 'lab'

    esxi_scg_ntp: true
    ntp1: '192.168.2.100'
    ntp2: '192.168.2.101'
    ntp3: '192.168.2.102'
    ntp4: '192.168.2.103'

    esxi_scg_lockdown: true
    esxi_scg_ssh: true

    vm_scg_disable_copy: true
    vm_scg_disable_paste: true
    vm_scg_disable_disk_shrink: true
    vm_scg_disable_disk_wiper: true
    vm_scg_disable_3d: true
    vm_scg_limit_vmrc: true
  collections:
    - daftpyposh.vspherescg
  tasks:
    - name: import ESXi role from a collection
      import_role:
        name: daftpyposh.vspherescg.esxi_scg
    - name: import VM role from a collection
      import_role:
        name: daftpyposh.vspherescg.vm_scg
