- name: Set SLP Disable
  vmware_host_service_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}" 
    validate_certs: no
    service_name: slpd
    state: absent
    service_policy: off
    