---
- name: Enable standard Lockdown Mode
  community.vmware.vmware_host_lockdown:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster_name: "{{ cluster_name }}"
    validate_certs: false
    state: present
