---
# defaults file for vm_scg

## Choose Setup
vm_scg_disable_copy: false
vm_scg_disable_paste: false
vm_scg_disable_disk_shrink: false
vm_scg_disable_disk_wiper: false
vm_scg_disable_3d: false
vm_scg_limit_vmrc: false
vm_scg_limit_setinfo: false
vm_scg_log_retention: false
vm_scg_log_rotation: false
vm_scg_restrict_host_info: false

## General
vcenter_hostname: 'vcenter.lab.local'
vcenter_username: 'Administrator@vsphere.local'
vcenter_password: 'C0mpl3x!'
cluster_name: 'lab'
