---
- name: Limit the number of console connections to one
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    cluster: "{{ cluster_name }}"
    uuid: "{{ item.uuid }}"
    advanced_settings:
      - key: "RemoteDisplay.maxConnections"
        value: "1"
  when: "'vCLS (' not in item.guest_name"
  with_items: "{{ vm_filtered }}"
