---
- name: Limit informational messages from the VM to the VMX file
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    cluster: "{{ cluster_name }}"
    uuid: "{{ item.uuid }}"
    advanced_settings:
      - key: "tools.setInfo.sizeLimit"
        value: "1048576"
  when: "'vCLS (' not in item.guest_name"
  with_items: "{{ vm_filtered }}"
