---
- name: Explicitly disable paste operations
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    cluster: "{{ cluster_name }}"
    uuid: "{{ item.uuid }}"
    advanced_settings:
      - key: "isolation.tools.paste.disable"
        value: "True"
  when: "'vCLS (' not in item.guest_name"
  with_items: "{{ vm_filtered }}"
